name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku container registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Check if Heroku app exists
        id: check_app
        run: |
          if heroku apps:info citadle-backend > /dev/null 2>&1; then
              echo "App exists"
              echo "::set-output name=exists::true"
          else
              echo "App does not exist"
              echo "::set-output name=exists::false"
          fi
        env:
          HEROKU_APP_NAME: citadle-backend
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Create Heroku app
        if: steps.check_app.outputs.exists == 'false'
        run: heroku create citadle-backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Docker image
        run: docker build -t registry.heroku.com/citadle-backend/web .

      - name: Push Docker image to Heroku container registry
        run: docker push registry.heroku.com/citadle-backend/web

      - name: Set environment variables
        run: |
          heroku config:set \
          NODE_ENV=${{ secrets.NODE_ENV }} \
          REDIS_HOST=${{ secrets.REDIS_HOST }} \
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
          API_KEY=${{ secrets.API_KEY }} \
          API_NINJA_KEY=${{ secrets.API_NINJA_KEY }} \
          API_NINJA_URL=${{ secrets.API_NINJA_URL }} \
          REST_COUNTRIES_URL=${{ secrets.REST_COUNTRIES_URL }} \
          MIN_CITY_POPULATION=${{ secrets.MIN_CITY_POPULATION }} \
          MIN_COUNTRY_POPULATION=${{ secrets.MIN_COUNTRY_POPULATION }} \
          CRON_EXPRESSION=${{ secrets.CRON_EXPRESSION }} \
          CRON_TIMEZONE=${{ secrets.CRON_TIMEZONE }} \
          --app citadle-backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Docker image to Heroku
        run: heroku container:release web --app citadle-backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
